show databases;
create schema pokemon_db;

create table poke_users(u_id int auto_increment primary key, 
username varchar (200) not null, 
email varchar(30) not null, password varchar (20) not null, 
xP int default 100 not null, status boolean default false not null, score int default 0);

create table poke_pokemons(p_id int primary key, p_name varchar (30) not null, 
p_type varchar(30), p_ability varchar (30), p_desc varchar (300), 
p_xP int default 1 not null, isGiga boolean default false not null);

insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (1,"Bulbasaur","Grass","Overgrow");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (2,"Ivysaur","Grass","Overgrow");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (3,"Venusaur","Grass","Overgrow");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (4,"Charmander","Fire","Blaze");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (5,"Charmeleon","Fire","Blaze");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (6,"Charizard","Fire","Blaze");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (7,"Squirtle","Water","Torrent");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (8,"Wartortle","Water","Torrent");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (9,"Blastoise","Water","Torrent");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (10,"Caterpie","Bug","Compound Eyes");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (11,"Metapod","Bug","Compound Eyes");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (12,"Butterfree","Bug","Compound Eyes");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (13,"Weedle","Bug","Shield Dust");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (14,"Kakuna","Bug","Shield Dust");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (15,"Beedrill","Bug","Shield Dust");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (16,"Pidgey","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (17,"Pidgeotto","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (18,"Pidgeot","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (19,"Rattata","Normal","Run Away");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (20,"Raticate","Normal","Run Away");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (21,"Spearow","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (22,"Fearow","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (23,"Ekans","Poison","Shed Skin");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (24,"Arbok","Poison","Shed Skin");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (25,"Pikachu","Electric","Static");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (26,"Raichu","Electric","Static");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (27,"Sandshrew","Ground","Sand Veil");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (28,"Sandslash","Ground","Sand Veil");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (29,"Nidoran","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (30,"Nidorina","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (31,"Nidoqueen","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (32,"Nidoran","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (33,"Nidorino","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (34,"Nidoking","Poison","Poison Point");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (35,"Clefairy","Fairy","Cute Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (36,"Clefable","Fairy","Cute Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (37,"Vulpix","Fire","Fire Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (38,"Ninetales","Fire","Fire Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (39,"Jigglypuff","Normal","Cute Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (40,"Wigglytuff","Normal","Cute Charm");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (41,"Zubat","Poison","Inner Focus");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (42,"Golbat","Poison","Inner Focus");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (43,"Oddish","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (44,"Gloom","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (45,"Vileplume","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (46,"Paras","Bug","Effect Spore");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (47,"Parasect","Bug","Effect Spore");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (48,"Venonat","Bug","Compound Eyes");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (49,"Venomoth","Bug","Compound Eyes");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (50,"Diglett","Ground","Sand Veil");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (51,"Dugtrio","Ground","Sand Veil");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (52,"Meowth","Normal","Pick Up");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (53,"Persian","Normal","Pick Up");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (54,"Psyduck","Water","Damp");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (55,"Golduck","Water","Damp");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (56,"Mankey","Fighting","Vital Spirit");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (57,"Primeape","Fighting","Vital Spirit");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (58,"Growlithe","Fire","Intimidate");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (59,"Arcanine","Fire","Intimidate");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (60,"Poliwag","Water","Damp");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (61,"Poliwhirl","Water","Damp");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (62,"Poliwrath","Water","Damp");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (63,"Abra","Psychic","Inner Focus");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (64,"Kadabra","Psychic","Inner Focus");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (65,"Alakazam","Psychic","Inner Focus");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (66,"Machop","Fighting","Guts");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (67,"Machoke","Fighting","Guts");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (68,"Machamp","Fighting","Guts");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (69,"Bellsprout","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (70,"Weepinbell","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (71,"Victreebel","Grass","Chlorophyll");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (72,"Tentacool","Water","Clear Body");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (73,"Tentacruel","Water","Clear Body");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (74,"Geodude","Rock","Rock Head");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (75,"Graveler","Rock","Rock Head");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (76,"Golem","Rock","Rock Head");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (77,"Ponyta","Fire","Run Away");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (78,"Rapidash","Fire","Run Away");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (79,"Slowpoke","Water","Oblivious");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (80,"Slowbro","Water","Oblivious");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (81,"Magnemite","Electric","Sturdy");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (82,"Magneton","Electric","Sturdy");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (83,"Farfetch'd","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (84,"Doduo","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (85,"Dodrio","Normal","Keen Eye");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (86,"Seel","Water","Thick Fat");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (87,"Dewgong","Water","Thick Fat");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (88,"Grimmer","Poison","Stench");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (89,"Muk","Poison","Stench");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (90,"Shellder","Water","Shell Armor");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (91,"Cloyster","Water","Shell Armor");
insert into poke_pokemons(p_id, p_name, p_type, p_ability) values (92,"Gastly","Ghost","Levitate");
